/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FreeTrialRouteImport } from './routes/free-trial'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdmissionFormRouteImport } from './routes/_authenticated/admission-form'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated/parent'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin/attendance'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin/fees'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/admin/lessons'
import { Route as AuthenticatedAdminRemarksRouteImport } from './routes/_authenticated/admin/remarks'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin/students'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalAnnouncementsRouteImport } from './routes/_authenticated/portal/announcements'
import { Route as AuthenticatedPortalAttendanceRouteImport } from './routes/_authenticated/portal/attendance'
import { Route as AuthenticatedPortalCoursesRouteImport } from './routes/_authenticated/portal/courses'
import { Route as AuthenticatedPortalFeesRouteImport } from './routes/_authenticated/portal/fees'
import { Route as AuthenticatedPortalLessonsRouteImport } from './routes/_authenticated/portal/lessons'
import { Route as AuthenticatedPortalMaterialsRouteImport } from './routes/_authenticated/portal/materials'
import { Route as AuthenticatedPortalProfileRouteImport } from './routes/_authenticated/portal/profile'
import { Route as AuthenticatedPortalProgressRouteImport } from './routes/_authenticated/portal/progress'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTrialRoute = FreeTrialRouteImport.update({
  id: '/free-trial',
  path: '/free-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmissionFormRoute =
  AuthenticatedAdmissionFormRouteImport.update({
    id: '/admission-form',
    path: '/admission-form',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRemarksRoute =
  AuthenticatedAdminRemarksRouteImport.update({
    id: '/remarks',
    path: '/remarks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAnnouncementsRoute =
  AuthenticatedPortalAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAttendanceRoute =
  AuthenticatedPortalAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCoursesRoute =
  AuthenticatedPortalCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFeesRoute = AuthenticatedPortalFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalLessonsRoute =
  AuthenticatedPortalLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMaterialsRoute =
  AuthenticatedPortalMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProfileRoute =
  AuthenticatedPortalProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalProgressRoute =
  AuthenticatedPortalProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/free-trial': typeof FreeTrialRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teachers': typeof TeachersRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admission-form': typeof AuthenticatedAdmissionFormRoute
  '/parent': typeof AuthenticatedParentRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/course/$slug': typeof CourseSlugRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/remarks': typeof AuthenticatedAdminRemarksRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/courses': typeof AuthenticatedPortalCoursesRoute
  '/portal/fees': typeof AuthenticatedPortalFeesRoute
  '/portal/lessons': typeof AuthenticatedPortalLessonsRoute
  '/portal/materials': typeof AuthenticatedPortalMaterialsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/progress': typeof AuthenticatedPortalProgressRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/free-trial': typeof FreeTrialRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teachers': typeof TeachersRoute
  '/admission-form': typeof AuthenticatedAdmissionFormRoute
  '/parent': typeof AuthenticatedParentRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/course/$slug': typeof CourseSlugRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/admin/remarks': typeof AuthenticatedAdminRemarksRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/portal/courses': typeof AuthenticatedPortalCoursesRoute
  '/portal/fees': typeof AuthenticatedPortalFeesRoute
  '/portal/lessons': typeof AuthenticatedPortalLessonsRoute
  '/portal/materials': typeof AuthenticatedPortalMaterialsRoute
  '/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/portal/progress': typeof AuthenticatedPortalProgressRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admission': typeof AdmissionRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/free-trial': typeof FreeTrialRoute
  '/gallery': typeof GalleryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/teachers': typeof TeachersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admission-form': typeof AuthenticatedAdmissionFormRoute
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/course/$slug': typeof CourseSlugRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/_authenticated/admin/remarks': typeof AuthenticatedAdminRemarksRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/portal/announcements': typeof AuthenticatedPortalAnnouncementsRoute
  '/_authenticated/portal/attendance': typeof AuthenticatedPortalAttendanceRoute
  '/_authenticated/portal/courses': typeof AuthenticatedPortalCoursesRoute
  '/_authenticated/portal/fees': typeof AuthenticatedPortalFeesRoute
  '/_authenticated/portal/lessons': typeof AuthenticatedPortalLessonsRoute
  '/_authenticated/portal/materials': typeof AuthenticatedPortalMaterialsRoute
  '/_authenticated/portal/profile': typeof AuthenticatedPortalProfileRoute
  '/_authenticated/portal/progress': typeof AuthenticatedPortalProgressRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/free-trial'
    | '/gallery'
    | '/pricing'
    | '/reset-password'
    | '/teachers'
    | '/admin'
    | '/admission-form'
    | '/parent'
    | '/pending'
    | '/portal'
    | '/course/$slug'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/lessons'
    | '/admin/remarks'
    | '/admin/students'
    | '/portal/announcements'
    | '/portal/attendance'
    | '/portal/courses'
    | '/portal/fees'
    | '/portal/lessons'
    | '/portal/materials'
    | '/portal/profile'
    | '/portal/progress'
    | '/admin/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/free-trial'
    | '/gallery'
    | '/pricing'
    | '/reset-password'
    | '/teachers'
    | '/admission-form'
    | '/parent'
    | '/pending'
    | '/course/$slug'
    | '/admin/attendance'
    | '/admin/fees'
    | '/admin/lessons'
    | '/admin/remarks'
    | '/admin/students'
    | '/portal/announcements'
    | '/portal/attendance'
    | '/portal/courses'
    | '/portal/fees'
    | '/portal/lessons'
    | '/portal/materials'
    | '/portal/profile'
    | '/portal/progress'
    | '/admin'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admission'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/free-trial'
    | '/gallery'
    | '/pricing'
    | '/reset-password'
    | '/teachers'
    | '/_authenticated/admin'
    | '/_authenticated/admission-form'
    | '/_authenticated/parent'
    | '/_authenticated/pending'
    | '/_authenticated/portal'
    | '/course/$slug'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/lessons'
    | '/_authenticated/admin/remarks'
    | '/_authenticated/admin/students'
    | '/_authenticated/portal/announcements'
    | '/_authenticated/portal/attendance'
    | '/_authenticated/portal/courses'
    | '/_authenticated/portal/fees'
    | '/_authenticated/portal/lessons'
    | '/_authenticated/portal/materials'
    | '/_authenticated/portal/profile'
    | '/_authenticated/portal/progress'
    | '/_authenticated/admin/'
    | '/_authenticated/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmissionRoute: typeof AdmissionRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  FreeTrialRoute: typeof FreeTrialRoute
  GalleryRoute: typeof GalleryRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeachersRoute: typeof TeachersRoute
  CourseSlugRoute: typeof CourseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-trial': {
      id: '/free-trial'
      path: '/free-trial'
      fullPath: '/free-trial'
      preLoaderRoute: typeof FreeTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admission-form': {
      id: '/_authenticated/admission-form'
      path: '/admission-form'
      fullPath: '/admission-form'
      preLoaderRoute: typeof AuthenticatedAdmissionFormRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lessons': {
      id: '/_authenticated/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/remarks': {
      id: '/_authenticated/admin/remarks'
      path: '/remarks'
      fullPath: '/admin/remarks'
      preLoaderRoute: typeof AuthenticatedAdminRemarksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/announcements': {
      id: '/_authenticated/portal/announcements'
      path: '/announcements'
      fullPath: '/portal/announcements'
      preLoaderRoute: typeof AuthenticatedPortalAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/attendance': {
      id: '/_authenticated/portal/attendance'
      path: '/attendance'
      fullPath: '/portal/attendance'
      preLoaderRoute: typeof AuthenticatedPortalAttendanceRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/courses': {
      id: '/_authenticated/portal/courses'
      path: '/courses'
      fullPath: '/portal/courses'
      preLoaderRoute: typeof AuthenticatedPortalCoursesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/fees': {
      id: '/_authenticated/portal/fees'
      path: '/fees'
      fullPath: '/portal/fees'
      preLoaderRoute: typeof AuthenticatedPortalFeesRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/lessons': {
      id: '/_authenticated/portal/lessons'
      path: '/lessons'
      fullPath: '/portal/lessons'
      preLoaderRoute: typeof AuthenticatedPortalLessonsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/materials': {
      id: '/_authenticated/portal/materials'
      path: '/materials'
      fullPath: '/portal/materials'
      preLoaderRoute: typeof AuthenticatedPortalMaterialsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/profile': {
      id: '/_authenticated/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof AuthenticatedPortalProfileRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/progress': {
      id: '/_authenticated/portal/progress'
      path: '/progress'
      fullPath: '/portal/progress'
      preLoaderRoute: typeof AuthenticatedPortalProgressRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRoute
  AuthenticatedAdminRemarksRoute: typeof AuthenticatedAdminRemarksRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRoute,
  AuthenticatedAdminRemarksRoute: AuthenticatedAdminRemarksRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAnnouncementsRoute: typeof AuthenticatedPortalAnnouncementsRoute
  AuthenticatedPortalAttendanceRoute: typeof AuthenticatedPortalAttendanceRoute
  AuthenticatedPortalCoursesRoute: typeof AuthenticatedPortalCoursesRoute
  AuthenticatedPortalFeesRoute: typeof AuthenticatedPortalFeesRoute
  AuthenticatedPortalLessonsRoute: typeof AuthenticatedPortalLessonsRoute
  AuthenticatedPortalMaterialsRoute: typeof AuthenticatedPortalMaterialsRoute
  AuthenticatedPortalProfileRoute: typeof AuthenticatedPortalProfileRoute
  AuthenticatedPortalProgressRoute: typeof AuthenticatedPortalProgressRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAnnouncementsRoute: AuthenticatedPortalAnnouncementsRoute,
  AuthenticatedPortalAttendanceRoute: AuthenticatedPortalAttendanceRoute,
  AuthenticatedPortalCoursesRoute: AuthenticatedPortalCoursesRoute,
  AuthenticatedPortalFeesRoute: AuthenticatedPortalFeesRoute,
  AuthenticatedPortalLessonsRoute: AuthenticatedPortalLessonsRoute,
  AuthenticatedPortalMaterialsRoute: AuthenticatedPortalMaterialsRoute,
  AuthenticatedPortalProfileRoute: AuthenticatedPortalProfileRoute,
  AuthenticatedPortalProgressRoute: AuthenticatedPortalProgressRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAdmissionFormRoute: typeof AuthenticatedAdmissionFormRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAdmissionFormRoute: AuthenticatedAdmissionFormRoute,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmissionRoute: AdmissionRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  FreeTrialRoute: FreeTrialRoute,
  GalleryRoute: GalleryRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeachersRoute: TeachersRoute,
  CourseSlugRoute: CourseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
